
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # have to Use credentials that can ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 240s


  ecom-user-server:
    build:
      context: ./ecom-user-server
      dockerfile: Dockerfile
    container_name: ecom-user-server
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "./wait-for-it.sh mysql:3306 -t 120 -- java -jar app.jar --spring.profiles.active=docker"

    ports:
      - "8081:8081"

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

    networks:
      - app-network
networks:
  app-network:
    driver: bridge
