apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-user-server
  labels:
    app: ecom-user-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-user-server
  template:
    metadata:
      labels:
        app: ecom-user-server
    spec:
      containers:
        - name: ecom-user-server
          image: mydocker723a/ecom-user-server:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: app-config-secret
                  key: spring-profile-active
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: JWT_EXPIRATION
              value: "3600"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: jdbcurl
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30