apiVersion: v1
kind: Service
metadata:
  name: ecom-user-server
  labels:
    app: ecom-user-server
spec:
  selector:
    app: ecom-user-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP